### ISSUE TITLE
Trip Planner Epic

### ISSUE THREAD

**Issue by smurph7894** [chingu-voyages/v45-tier3-team-53#15]
**__Feature Description__**
track hotel, restaurant, transportation, activities.

**__Major User Stories/tasks__**
- [ ] As a user I should be able to login to my account.
- [ ] As a user I should be able to create/edit my user profile.
- [ ] As a user I should be able to create a new trip.
- [ ] As a user I should be able to see a list or screen of all my trips.
- [ ] As a user I should be able to add another user to my trip.
- [ ] As a user I should be able to add hotels to my trip.
- [ ] As a user I should be able to add restaurants/activities to my trip.
- [ ] As a user I should be able to add transportation to my trip.
- [ ] As a user I should be able to view my trip agenda.

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
- #24 
- #23 
- #22 
- #21 
- #20 
- #19 
- #18 
- #17 
- #16
