### ISSUE TITLE
Update task model to include destination information

### ISSUE THREAD

**Issue by shawnkoong** [chingu-voyages/v45-tier3-team-53#48]
**__Task Description__**
The trip model needs to have a reference to the destination of the trip with details about this destination.

Mainly, the extra information needed are:

- [ ] destination name/address
- [ ] destination coordinate (will be used to locate within google map)
- [ ] destination viewport coordinates (will be used to set the coordinate bounds to show destination in the map)

**__Acceptance Criteria__**
The above things should be included either directly or indirectly into the trip, as creating a new trip will include these information.

More information about what is provided by Google [here](https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResult)

**Comment by shawnkoong** [comment]
Name/address will be a string
All coordinates will be a pair of numbers that can be casted into doubles
